server:
  port: 8080
spring:
  application:
    name: Financas Pessoais Backend
  cloud:
    vault:
      uri: ${VAULT_ADDR}
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secrets
        application-name: financas-pessoais
    compatibility-verifier:
      enabled: false
  config:
    import: vault://
  datasource:
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
#  flyway:
#    enabled: false
#    baseline-on-migrate: false
#    locations:
#      classpath: /db/migration